-- Must be run manually
CREATE DATABASE onlineshopdatabase;

-- It is autogenerated on the first run
CREATE TABLE products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(1000),
    category VARCHAR(255),
    subcategory VARCHAR(255),
    seller_name VARCHAR(255),
    price FLOAT,
    quantity INT
);
